name: npm-pkg-lint
author: David Sveningsson
description: |
  Opinionated linter for NPM package tarball and package.json metadata

branding:
  icon: git-pull-request
  color: blue

inputs:
  allow-dependencies:
    description: Comma-separated list of dependencies to explicitly allow even if they would yield an error
    required: false
    default: ""
  allow-files:
    description: Comma-separated list of filenames or globs to explicitly allow in tarball even if they would yield an error
    required: false
    default: ""
  build:
    description: Build command (executed with `npm run`)
    required: false
    default: build
  folders:
    description: Space-separated list of folder to run in.
    required: false
    default: "."
  ignore-node-version:
    description: Ignore error for outdated node version (see `--ignore-node-version` CLI argument)
    required: false
    default: ""
  npm-pack:
    description: When enabled `npm pack` is run automatically
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Setup cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: ~/.cache/npm-pkg-lint
        key: npm-pkg-lint
    - name: Build package
      if: (inputs.build != 'false' && inputs.build != false)
      shell: bash
      run: npm run --if-present ${{ inputs.build }}
    - name: Create NPM package
      if: (inputs.npm-pack == 'true' || inputs.npm-pack == true)
      shell: bash
      run: |
        for pkg in ${{ inputs.folders }}; do (
          set -e
          if [[ "${pkg}" != "." ]]; then
            cd $pkg
            name=$(node -p 'require("./package.json").name')
            echo "::group::${name}"
          fi
          npm pack
          if [[ "${pkg}" != "." ]]; then
            echo "::endgroup::"
          fi
        ); done
    - name: npm-pkg-lint
      shell: bash
      env:
        ALLOW_DEPENDENCIES: ${{ inputs.allow-dependencies }}
        ALLOW_FILES: ${{ inputs.allow-files }}
        IGNORE_NODE_VERSION: ${{ inputs.ignore-node-version }}
      run: |
        for pkg in ${{ inputs.folders }}; do (
          set -e
          if [[ "${pkg}" != "." ]]; then
            cd $pkg
            name=$(node -p 'require("./package.json").name')
            echo "::group::${name}"
            echo Running npm-pkg-lint on package ${name} in ${pkg}
          fi
          args=()
          if [[ -n "${ALLOW_DEPENDENCIES}" ]]; then
            args+=("--allow-dependency=${ALLOW_DEPENDENCIES}")
          fi
          if [[ -n "${ALLOW_FILES}" ]]; then
            args+=("--allow-file=${ALLOW_FILES}")
          fi
          if [[ -n "${IGNORE_NODE_VERSION}" ]]; then
            args+=("--ignore-node-version=${IGNORE_NODE_VERSION}")
          fi
          npm exec npm-pkg-lint -- "${args[@]}"
          if [[ "${pkg}" != "." ]]; then
            echo "::endgroup::"
          fi
        ); done
